Repository BorryJJong/KnockKnock-iOS, pull requests merged in 2022-05, with the labels that each got.

#7 [FEAT] VIP 기본 구조 구성 추가
  KnockKnock-iOS.xcodeproj/project.pbxproj
  KnockKnock-iOS/Entity/Challenge.swift
  KnockKnock-iOS/Repository/ChellengeRepository.swift
  KnockKnock-iOS/Scenes/BaseComponent/BaseCollectionViewCell.swift
  KnockKnock-iOS/Scenes/Cells/ChallengeCell.swift
  KnockKnock-iOS/Scenes/Challenge/ChallengeInteractor.swift
  KnockKnock-iOS/Scenes/Challenge/ChallengePresenter.swift
  KnockKnock-iOS/Scenes/Challenge/ChallengeRouter.swift
  KnockKnock-iOS/Scenes/Challenge/ChallengeViewController.swift
  KnockKnock-iOS/Scenes/Challenge/ChallengeWorker.swift
Labels: sangwon 🥶, feat

#10 #9 feat bottom sheet init
  KnockKnock-iOS.xcodeproj/project.pbxproj
  KnockKnock-iOS/Scenes/BottomSheetView.swift
  KnockKnock-iOS/Scenes/BottomSheetViewController.swift
  KnockKnock-iOS/Scenes/Cells/BottomMenuCell.swift
  KnockKnock-iOS/Scenes/Challenge/ChallengeViewController.swift
Labels: daye 😀, feat, review complete

#13 [ CHORE] swiftlint 적용
  .swiftlint.yml
  KnockKnock-iOS.xcodeproj/project.pbxproj
  KnockKnock-iOS/AppDelegate.swift
  KnockKnock-iOS/Entity/Property.swift
  KnockKnock-iOS/Extension-Utilities/Foundation/Array+Ext.swift
  KnockKnock-iOS/Extension-Utilities/UIKit/UIButton+Ext.swift
  KnockKnock-iOS/Extension-Utilities/UIKit/UITableView+Ext.swift
  KnockKnock-iOS/Repository/ChellengeRepository.swift
  KnockKnock-iOS/SceneDelegate.swift
  KnockKnock-iOS/Scenes/BaseComponent/BaseTableViewCell.swift
  KnockKnock-iOS/Scenes/Cells/AddressCell.swift
  KnockKnock-iOS/Scenes/Cells/PhotoCell.swift
  KnockKnock-iOS/Scenes/Cells/PropertyCell.swift
  KnockKnock-iOS/Scenes/Feed/FeedWrite/FeedWritePresenter.swift
  KnockKnock-iOS/Scenes/Feed/FeedWrite/FeedWriteViewController.swift
  KnockKnock-iOS/Scenes/Feed/FeedWrite/PropertySelectViewController.swift
  KnockKnock-iOS/Scenes/Feed/FeedWrite/ShopSearchViewController.swift
  KnockKnock-iOS/Scenes/Feed/FeedWrite/Views/FeedWriteView.swift
  KnockKnock-iOS/Scenes/Feed/FeedWrite/Views/shopSearchView.swift
  KnockKnock-iOS/Scenes/Home/HomeViewController.swift
Labels: sangwon 🥶, review needed, chore
